// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC97MFO_VJxn2WL_rIhZ_zqNxnoaxxwa9I',
    appId: '1:321733913852:web:5a12d218f03f4effdbbb79',
    messagingSenderId: '321733913852',
    projectId: 'flutterfire-ui-codelab-11da0',
    authDomain: 'flutterfire-ui-codelab-11da0.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-11da0.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZ6fz8p5sUakz7b6UC29moGrVcKdKP3w',
    appId: '1:321733913852:android:e862827d6ad6216adbbb79',
    messagingSenderId: '321733913852',
    projectId: 'flutterfire-ui-codelab-11da0',
    storageBucket: 'flutterfire-ui-codelab-11da0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBNkoyiuAD-V4aKaVMg0uybrF1bj87VI',
    appId: '1:321733913852:ios:a5d90bd9f5546c5bdbbb79',
    messagingSenderId: '321733913852',
    projectId: 'flutterfire-ui-codelab-11da0',
    storageBucket: 'flutterfire-ui-codelab-11da0.appspot.com',
    iosClientId: '321733913852-9dfi2pjo4s4sc0reose7fcouqlpol3ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBNkoyiuAD-V4aKaVMg0uybrF1bj87VI',
    appId: '1:321733913852:ios:a5d90bd9f5546c5bdbbb79',
    messagingSenderId: '321733913852',
    projectId: 'flutterfire-ui-codelab-11da0',
    storageBucket: 'flutterfire-ui-codelab-11da0.appspot.com',
    iosClientId: '321733913852-9dfi2pjo4s4sc0reose7fcouqlpol3ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

}